# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: roda-rest_api 2.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "roda-rest_api"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Michel Benevento"]
  s.date = "2015-06-29"
  s.description = "Create restful API easily with the Roda framework"
  s.email = "michelbenevento@yahoo.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/roda/plugins/rest_api.rb",
    "lib/roda/rest_api.rb",
    "roda-rest_api.gemspec",
    "test/rest_api_api_test.rb",
    "test/rest_api_form_input_test.rb",
    "test/rest_api_id_pattern_test.rb",
    "test/rest_api_nested_test.rb",
    "test/rest_api_perf_benchmark.rb",
    "test/rest_api_permit_test.rb",
    "test/rest_api_resource_test.rb",
    "test/rest_api_routes_test.rb",
    "test/rest_api_serialize_test.rb",
    "test/rest_api_singleton_test.rb",
    "test/rest_api_split_route_test.rb",
    "test/rest_api_upgrade_test.rb",
    "test/rest_api_wrapper_test.rb",
    "test/test_helpers.rb"
  ]
  s.homepage = "http://github.com/beno/roda-rest_api"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Restful resources for Roda"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<roda>, ["~> 2"])
    else
      s.add_dependency(%q<roda>, ["~> 2"])
    end
  else
    s.add_dependency(%q<roda>, ["~> 2"])
  end
end

